/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package introduccion;

public class App {
  public static void main(String[] args) {
    int result = add(2, 5, 6);
    System.out.println(result);

    Coche miCoche = new Coche();
    miCoche.incrementarPuertas();
    System.out.println(miCoche.numeroPuertas);
  }

  public static int add(int n1, int n2, int n3) {
    return n1 + n2 + n3;
  }
}
